### ISSUE TITLE
Backlinks

### ISSUE THREAD

**Issue by stopsopa** [tom-on-the-internet/fetch-demonstration#1]
Hi, Why don't you backlink the [article](https://tomontheinternet.com/why-two-awaits/) and the [video](https://www.youtube.com/watch?v=Ki64Cnyf_cA) to the repo?

**Comment by tom-on-the-internet** [comment]
@stopsopa Thanks for the idea!
I've done this.
https://github.com/tom-on-the-internet/fetch-demonstration/commit/fdc182b6a69077cc253d35d0cdff56239cc2d872
